### ISSUE TITLE
after installed this there is an issue came in node window after build successfully completed can you pls check that

### ISSUE THREAD

**Issue by tejasspublishers** [ck3g/BlitzReading#11]
──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   C:\tution\BlitzReading\node_modules\react-native\scripts
Error: Unable to resolve module `./index` from `C:\tution\BlitzReading\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\tution\BlitzReading\node_modules\react-native\scripts/.`. Indeed, none of these files exist:
  * `C:\tution\BlitzReading\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\tution\BlitzReading\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\tution\BlitzReading\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\tution\BlitzReading\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\tution\BlitzReading\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at C:\tution\BlitzReading\node_modules\metro\src\lib\transformHelpers.js:261:42
    at Server.<anonymous> (C:\tution\BlitzReading\node_modules\metro\src\Server.js:1038:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\tution\BlitzReading\node_modules\metro\src\Server.js:99:24)
    at _next (C:\tution\BlitzReading\node_modules\metro\src\Server.js:119:9)
::ffff:127.0.0.1 - - [14/Apr/2019:20:05:57 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

**Comment by tejasspublishers** [comment]
Someone found the issue: 
https://stackoverflow.com/questions/55322133/problem-with-react-native-init-template-app-unable-to-resolve-module-index

**Comment by ck3g** [comment]
Hey @tejasspublishers is that still relevant?
